<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.5 setup script
 * Date: Thu, 29 Sep 2011 07:06:11 +0400
 */

/* Servers configuration */
$i = 0;

/* Server: db_user [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'db_user';
$cfg['Servers'][$i]['host'] = '46.4.248.175';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['ssl'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '4e83e03c7c5576.44594394';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>